//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and
//     will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Utilities.Courses {
public partial class QHelper {
public static string GetFellowship(Random random, Action<string, ushort> registerAnswer, bool isProof) {
var q = new XyzQuestion(random, isProof);
q.Id = "GetFellowship";
q.Marks = 1;
q.Stem = @"
      Which of these following were part of the group 
      known as the Fellowship of the Ring?
   ";
q.AddCorrects(
   @"Peregrin Took",
   @"Samwise Gamgee",
   @"Meriadoc Brandybuck",
   @"Aragorn",
   @"Boromir",
   @"Legolas",
   @"Gandalf",
   @"Gimli",
   @"Frodo Baggins"
);
q.AddIncorrects(
   @"Bilbo Baggins",
   @"Adelard Took",
   @"Belba Bolger",
   @"Camellia Sackville",
   @"Elfstan",
   @"Ferumbras",
   @"Ferdinand",
   @"Gormadoc",
   @"Isumbras",
   @"Orgulas",
   @"Sigismond",
   @"Tom Bombadil",
   @"Túrin Turambar",
   @"Khîm",
   @"Ibûn",
   @"Faramir",
   @"Gríma",
   @"Elrond",
   @"Galadriel",
   @"Shelob",
   @"Finarfin",
   @"Eärwen"
);
string rval = q.GetQuestion(registerAnswer);
return rval;
} // GetFellowship
} // class
} // namespace
