//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and
//     will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Utilities.Courses {
public partial class QHelper {
public static string GetPrancingPonyPerson(Random random, Action<string, ushort> registerAnswer, bool isProof) {
var q = new TruthQuestion(random, isProof);
q.Id = "GetPrancingPonyPerson";
q.Marks = 1;
q.Stem = @"
      Who did Sam, Frodo, Pippin and Merry meet at the
      Prancing Pony on their way to Rivendell carrying the ring?
   ";
q.AddCorrects(
   @"Aragorn",
   @"Strider"
);
q.AddIncorrects(
   @"Gandalf",
   @"Bilbao",
   @"Saruman",
   @"Thorin",
   @"Arwen",
   @"Lúthien",
   @"Celeborn",
   @"Fëanor",
   @"Celebrimbor",
   @"Narvi",
   @"Elu Thingol",
   @"Elendil"
);
string rval = q.GetQuestion(registerAnswer);
return rval;
} // GetPrancingPonyPerson
} // class
} // namespace
