//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and
//     will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Utilities.Courses {
public partial class QHelper {
public static string QId1(Random random, Action<string, ushort> registerAnswer, bool isProof) {
var q = new XyzQuestion(random, isProof);
q.Id = "QId1";
q.Marks = 2;
q.Stem = @"
      ?
   ";
q.AddCorrects(
   @"",
   @"",
   @"",
   @"",
   @"",
   @""
);
q.AddIncorrects(
   @"",
   @"",
   @"",
   @"",
   @"",
   @""
);
string rval = q.GetQuestion(registerAnswer);
return rval;
} // QId1
} // class
} // namespace
